### ISSUE TITLE
Rookie numbers

### ISSUE THREAD

**Issue by romanZupancic** [CSC207-UofT/lab-3-trader-lenobo#10]
These are rookie numbers
![image](https://user-images.githubusercontent.com/33498090/134999588-b4885dc9-67a4-40db-a159-153d2e327f05.png).

We gotta get these numbers up

**Comment by anadjianto** [comment]
![image](https://user-images.githubusercontent.com/71408986/134999681-3d4a887d-8253-44f1-9b7d-9b3f1fb45c81.png)

**Comment by nathan-hansen** [comment]
on it boss :sunglasses: numbers goin up !

**Comment by romanZupancic** [comment]
Numbers are up
